// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"project/internal/application/repositories"
	"project/internal/application/services/links"
	"project/internal/controllers/link_handlers"
	"project/internal/infrastructure"
	"project/internal/settings"
)

// Injectors from wire.go:

func InitializeHandler(config *settings.Config) (*linkhandlers.LinkHandler, error) {
	db, err := infrastructure.NewPsqlDB(config)
	if err != nil {
		return nil, err
	}
	linksDbRepo := infrastructure.NewLinksDbRepo(db)
	client, err := infrastructure.NewRedisConnection(config)
	if err != nil {
		return nil, err
	}
	cachedRepo := infrastructure.NewCachedRepo(linksDbRepo, client, config)
	linkService := links.NewLinkService(cachedRepo)
	linkHandler := linkhandlers.NewLinkHandler(linkService)
	return linkHandler, nil
}

// wire.go:

var RepoSet = wire.NewSet(infrastructure.NewPsqlDB, infrastructure.NewLinksDbRepo, infrastructure.NewRedisConnection, infrastructure.NewCachedRepo, wire.Bind(new(repositories.ILinksRepo), new(*infrastructure.CachedRepo)))

var ServiceSet = wire.NewSet(links.NewLinkService, wire.Bind(new(links.ILinkService), new(*links.LinkService)))

var HandlerSet = wire.NewSet(linkhandlers.NewLinkHandler)
