//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.
// Run `wire` in this package to regenerate.

package di

import (
	"project/internal/application/repositories"
	"project/internal/application/services/links"
	linkhandlers "project/internal/controllers/link_handlers"
	"project/internal/infrastructure"

	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeHandler() (*linkhandlers.LinkHandler, error) {
	linksInMemoryRepo := infrastructure.NewLinksInMemoryRepo()
	linkService := links.NewLinkService(linksInMemoryRepo)
	linkHandler := linkhandlers.NewLinkHandler(linkService)
	return linkHandler, nil
}

// Sets declared in wire.go (kept so the file compiles with the wire import).

var _ = wire.NewSet
var _ repositories.ILinksRepo = (*infrastructure.LinksInMemoryRepo)(nil)
var _ links.ILinkService = (*links.LinkService)(nil)
